name: "Functionnal tests"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  func-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.14.1
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - run: npx serve . &
      - run: npm run func-test
      - run: echo "::error Failed functionnary test, git gud"
        if: failure()   