name: "Lint"
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run:  npm install
      - run: npm run lint > lint.log
      - run: | 
        curl -X POST ${{ secrets.DISCORD_GITHUB }} -H "Content-Type: application/json" -d '{"content":"Linter found problems"}'
        if: failure()
      - run: |
        curl -X POST ${{ secrets.DISCORD_GITHUB }} -H "Content-Type: application/json" -d '{"content":"Linter found no problems"}'
        if: success()
